(* begin-documentation-node
############
  Examples
############


.. toctree::
   :maxdepth: 2
   :caption: Development:
   :includehidden:

   ../Course/A    <A.rst>
   ../Course/B    <B.rst>
   ../Course/C    <C.rst>
   ../Course/D    <D.rst>
   ../Course/E    <E.rst>

A course of programming examples starts here...

https://github.com/io-core/Examples/blob/main/Course.Mod

end-documentation-node *)


(* begin-package-description
### _Package Overview:_
The Course package manages:
* Showing how to program in Oberon
### _Package Use:_

Explanation...

### _Modules in this package:_
end-package-description *)

(* begin-module-use-description
Module Course handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Course; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Course.
